import sys, pandas as pd, numpy as np
c = sys.argv[1]; out = sys.argv[2]
d = pd.read_csv(f'{c}/districts.csv'); p = pd.read_csv(f'{c}/properties.csv')
cols = {'district_id':'neighborhood_id','name_ar':'name_ar','name_en':'name_en','region':'region','lat':'latitude','lon':'longitude',
 'schools':'schools_count','schools_primary':'schools_primary','schools_middle':'schools_middle','schools_secondary':'schools_secondary',
 'hospitals':'hospitals_count','parks':'parks_count','gyms':'gyms_count','pharmacies':'pharmacies_count','supermarkets':'supermarkets_count',
 'shopping_centers':'shopping_centers_count','banks':'banks_count','fuel_stations':'fuel_stations_count','metro_stations':'metro_stations_count',
 'moj_median_price_m2':'median_price_m2','moj_deals':'deals_count','aqar_median_price':'median_property_price',
 'aqar_median_price_apartment':'median_apartment_price','aqar_median_price_villa':'median_villa_price','aqar_median_price_floor':'median_floor_price','aqar_listings':'listings_count'}
d = d[list(cols)].rename(columns=cols)
p = p.rename(columns={'district_id':'neighborhood_id'})
def lit(v):
    if v is None or (isinstance(v, float) and np.isnan(v)): return 'NULL'
    if isinstance(v, (int, np.integer)): return str(int(v))
    if isinstance(v, (float, np.floating)): return str(int(v)) if float(v).is_integer() else repr(round(float(v), 6))
    return "'" + str(v).replace('\\','\\\\').replace("'", "''") + "'"
def inserts(table, df):
    rows = [f"({', '.join(lit(v) for v in r)})" for r in df.astype(object).itertuples(index=False)]
    return f"INSERT INTO {table} ({', '.join(df.columns)}) VALUES\n" + ',\n'.join(rows) + ';\n'
with open(out, 'w', encoding='utf-8') as f:
    f.write('-- Diyara data: neighborhoods and properties built from the GP1 datasets (generated by data/scripts/build_districts.py)\nUSE diyara;\nSET NAMES utf8mb4;\n\nDELETE FROM properties;\nDELETE FROM neighborhoods;\n\n')
    f.write(inserts('neighborhoods', d)); f.write('\n'); f.write(inserts('properties', p))
print(len(d), len(p))
